/*
 * This file was generated by the Gradle "init" task.
 */

dependencies {
  api(project(":bytle-db-jdbc"))
  api(project(":bytle-db"))
  api(project(":bytle-log"))
  // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
  api("org.xerial:sqlite-jdbc:3.43.0.0")
  testImplementation(project(":bytle-db-gen"))
  testImplementation(project(":bytle-db-jdbc","test"))
  testImplementation(project(":bytle-test"))
}

description = "Db Sqlite"
