/*
 * This file was generated by the Gradle "init" task.
 */

dependencies {
    compile(project(":bytle-db-jdbc"))
    compile(project(":bytle-db"))
    compile(project(":bytle-log"))
    compile("org.xerial:sqlite-jdbc:3.30.1")
}

description = "Db Sqlite"
