/*
 * This file was generated by the Gradle "init" task.
 */
// ojdbc8 means certified with jdk8
dependencies {
  compile(project(":bytle-db-jdbc"))
  compile("com.oracle.ojdbc:ojdbc8:19.3.0.0") // for the types
  testRuntimeOnly( "com.oracle.ojdbc:ojdbc8:19.3.0.0")
  testCompile( "org.testcontainers:oracle-xe:1.12.5")
}

description = "Db Oracle"
