/*
 * This file was generated by the Gradle "init" task.
 */

allprojects {

  group = "net.bytle"
  version = "0.0.1-SNAPSHOT"

}

// because we are not using it and that a lot of project are
// We get no error when compiling, excluding it shows an error where it"s used.


subprojects {

  apply(plugin = "java")
//    sourceCompatibility = JavaVersion.VERSION_1_8


  repositories {
    mavenLocal()
    maven {
      url = java.net.URI("https://repo.maven.apache.org/maven2")
    }
    maven {
      // for oracle jdbc
      // url = "https://repo.boundlessgeo.com/main/"
      url = java.net.URI("http://maven.icm.edu.pl/artifactory/repo/")
    }
  }

  dependencies {
    "testCompile"("junit:junit:4.12")
    "testCompile"("com.github.stefanbirkner:system-rules:1.17.0")
    "testCompile"("org.testcontainers:testcontainers:1.12.5")
    // https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api
    "runtimeOnly"("org.apache.logging.log4j:log4j-api:2.13.0")
    "runtimeOnly"("org.apache.logging.log4j:log4j-core:2.13.0")
    "runtimeOnly"("org.apache.logging.log4j:log4j-slf4j-impl:2.13.0")
    "compile"("org.slf4j:slf4j-api:1.7.30")
  }




}

// samples/testing/testReport in the full Gradle distribution
// doc: https://docs.gradle.org/current/userguide/java_testing.html#test_reporting
// The problem with this publication is that if there is an error in the test you don"t get anything
