version: '3'

tasks:
  # When developing, compile and run
  install:
    # -DskipTests and not -Dmaven.test.skip so that test packaging is not skipped
    cmds:
      - mvn install -DskipTests
  package:
    # -DskipTests and not -Dmaven.test.skip so that test packaging is not skipped
    cmds:
      - mvn package -DskipTests
  # Run tests slow excluded (by default)
  test:
    cmds:
      # -P for profile name
      - |
        mvn test -P default
  # Run all tests
  test-all:
    cmds:
      # -P for profile name
      - |
        mvn test -P all-tests
  # Run slow tests
  test-slow:
    cmds:
      # -P for profile name
      - |
        mvn test -P slow-tests-only
  # Install tabulify locally
  # the root `install` command install the jars
  install-cli:
    cmds:
      - contrib/script/install-cli
  # Start a whole test cycle
  # Restart with: mvn install --resume-from tabulify-data-generation
  install-test:
    cmds:
      - mvn install
  # Start the documentation website
  start-web:
    cmds:
      - |
        docker run \
        --name site-com-tabulify \
        --rm \
        -d \
        -p 8081:80 \
        --user 1000:1000 \
        -e DOKU_DOCKER_ENV=dev \
        -e DOKU_DOCKER_ACL_POLICY='public' \
        -e DOKU_DOCKER_ADMIN_NAME='admin' \
        -e DOKU_DOCKER_ADMIN_PASSWORD='welcome' \
        -e DOKU_DOCKER_BASE_URL='http://localhost:8081' \
        -v {{.TASKFILE_DIR}}/tabulify-cli/src/main/tabulify.com:/var/www/html \
        ghcr.io/combostrap/dokuwiki:php8.3-latest

