logicalName: loadUser
pipeline:
  - name: 'SelectUsersCsv'
    description: 'Select the users data path'
    operation: select
    arguments: # alias for arguments
      data-selector: data/users.csv
      not-strict: false

  - name: 'LoadUserCsv'
    op: copy
    arguments:
      targetUri: stg_users@sqlite
      target-operation: drop



