openapi: 3.0.3
info:
  description: |
    This is a non-stable API for the [combostrap application](https://combostrap.com)

    If you need a stable API to manage combostrap,
    check the [official API](https://api.combostrap.com)
  title: ComboStrap Private API
  version: v2023-06-18
servers:
- url: https://api.eraldy.com/combo/_private
security:
- apiKeyAuth: []
tags:
- description: Env data
  name: env
- description: Operations on realm
  name: realm
- description: Operations about users
  name: user
- description: "Operations about list management (creation, registration)"
  name: list
- description: Operations on app
  name: app
- description: Operations on list registration
  name: registration
- description: Analytics operation
  name: analytics
- description: Public API Token creation
  name: token
paths:
  /env:
    get:
      operationId: envGet
      summary: Return environment data
      tags:
      - env
      x-accepts: application/json
  /ping:
    get:
      operationId: pingGet
      security: []
      summary: A health check endpoint
      tags:
      - health
      x-accepts: application/json
  /realm:
    get:
      operationId: realmGet
      summary: Return the realm for the request
      tags:
      - realm
      x-accepts: application/json
    post:
      operationId: realmPost
      security:
      - apiKeyAuth:
        - write:realm
      summary: Create a realm
      tags:
      - realm
      x-content-type: application/json
      x-accepts: application/json
  /realms:
    get:
      operationId: realmsGet
      security:
      - apiKeyAuth:
        - read:realm
      summary: Return the list of realms for the connected user
      tags:
      - realm
      x-accepts: application/json
  /realms/owned-by/{userGuid}:
    get:
      operationId: realmsOwnedByGet
      security:
      - apiKeyAuth:
        - read:realm
      summary: Return the list of realms owned by the user
      tags:
      - realm
      x-accepts: application/json
  /realm/{realmGuid}/users/new:
    get:
      operationId: realmUsersNewGet
      security:
      - apiKeyAuth:
        - read:realm
      summary: Return the list of recent new users for the realm
      tags:
      - realm
      x-accepts: application/json
  /services:
    get:
      operationId: servicesGet
      security:
      - apiKeyAuth:
        - read:service
      summary: Get all services
      tags:
      - service
      x-accepts: application/json
  /campaign/email:
    post:
      operationId: campaignEmailPost
      security:
      - apiKeyAuth:
        - write:campaign
      summary: Create an email campaign
      tags:
      - campaign
      x-content-type: application/json
      x-accepts: application/json
  /service:
    get:
      operationId: serviceGet
      security:
      - apiKeyAuth:
        - read:service
      summary: Retrieve a service by guid or uri
      tags:
      - service
      x-accepts: application/json
  /service/smtp:
    post:
      operationId: serviceSmtpPost
      security:
      - apiKeyAuth:
        - write:service
      summary: Create a SMTP mail service for a app or a user
      tags:
      - service
      x-content-type: application/json
      x-accepts: application/json
  /app:
    get:
      operationId: appGet
      security:
      - apiKeyAuth:
        - read:app
      summary: |
        Retrieve an app by:
        * id with the appGuid
        * or by name with the appUri and realm (Handle or Guid)
      tags:
      - app
      x-accepts: application/json
    post:
      operationId: appPost
      security:
      - apiKeyAuth:
        - write:app
      summary: "Create or modify an app (ie design, ...)"
      tags:
      - app
      x-content-type: application/json
      x-accepts: application/json
  /apps:
    get:
      operationId: appsGet
      security:
      - apiKeyAuth:
        - read:app
      summary: List apps for a realm
      tags:
      - app
      x-accepts: application/json
  /user/auth:
    get:
      operationId: userAuthGet
      summary: Return the authenticated user
      tags:
      - user
      x-accepts: application/json
  /user:
    get:
      operationId: userGet
      security:
      - apiKeyAuth:
        - read:user
      summary: |
        Get a user by guid or email
      tags:
      - user
      x-accepts: application/json
    post:
      operationId: userPost
      security:
      - apiKeyAuth:
        - write:user
      summary: Create or modify a user (a guid or a email should be given)
      tags:
      - user
      x-content-type: application/json
      x-accepts: application/json
  /user/{guid}:
    get:
      operationId: userGuidGet
      security:
      - apiKeyAuth:
        - read:user
      summary: |
        Get a user by guid

        If you want to use the email has identifier,
        you should use the `userGet` operation passing the email as query parameter
      tags:
      - user
      x-accepts: application/json
  /users:
    get:
      operationId: usersGet
      security:
      - apiKeyAuth:
        - read:user
      summary: List users
      tags:
      - user
      x-accepts: application/json
  /list:
    get:
      operationId: listGet
      security:
      - apiKeyAuth:
        - write:read
      summary: |
        Get list information

        Access by:
        * id with the listGuid
        * name with the listHandle and realmHandle
      tags:
      - list
      x-accepts: application/json
    post:
      operationId: listPost
      security:
      - apiKeyAuth:
        - write:list
      summary: Create a list where users can register
      tags:
      - list
      x-content-type: application/json
      x-accepts: application/json
  /lists:
    get:
      operationId: listsGet
      security:
      - apiKeyAuth:
        - read:list
      summary: |
        Get a list of lists

        The app should be given via:
          - the appGuid
          - or the appUri along with the realmGuid or realmHandle
      tags:
      - list
      x-accepts: application/json
  /lists/summary:
    get:
      operationId: listsSummaryGet
      security:
      - apiKeyAuth:
        - read:list
      summary: Get a list of list in a summary format
      tags:
      - list
      x-accepts: application/json
  /list/registration:
    get:
      description: |
        Get a registration
          * by id with the registrationGuid
          * by name with the subscriberEmail and listGuid
      operationId: listRegistrationGet
      security:
      - apiKeyAuth:
        - read:list
      summary: Get a registration object
      tags:
      - registration
      x-accepts: application/json
  /list/registration/validation:
    get:
      operationId: listRegistrationValidationGet
      security: []
      summary: |
        The URI of the validation link in the validation
        letter that the user receive.
        The user needs to click this link to confirm her/his registration.
      tags:
      - registration
      x-accepts: text/html
  /list/registration/letter/confirmation:
    get:
      operationId: listRegistrationLetterConfirmationGet
      security:
      - apiKeyAuth:
        - read:list
      summary: |
        Return the confirmation letter after the user has clicked on the validation link.

        To get a confirmation as it's show to a user, you just need to set
        the subscriber name and the list guid

        The other parameters will overwrite other list information.
      tags:
      - registration
      x-accepts: text/html
  /list/registration/letter/validation:
    get:
      operationId: listRegistrationLetterValidationGet
      security:
      - apiKeyAuth:
        - read:list
      summary: |
        Return the validation letter with a validation link as send by email.
      tags:
      - registration
      x-accepts: text/html
  /list/registrations:
    get:
      operationId: listRegistrationsGet
      security:
      - apiKeyAuth:
        - read:list
      summary: List the registrations for a list
      tags:
      - registration
      x-accepts: application/json
components:
  securitySchemes:
    cookieAuth:
      in: cookie
      name: cs-session-id
      type: apiKey
    apiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey
