package com.tabulify.crypto.util;

import java.nio.charset.StandardCharsets;
import java.util.Random;


/**
 * Static utility class around Bytes
 *
 */
public class BytesUtil {


    /**
     * A wrapper around {@link Byte#parseByte(String)}
     */
    @SuppressWarnings("unused")
    Byte fromString(String s) {
        return Byte.parseByte(s);
    }


    /**
     * Byte to UTF-8 String
     *
     * @return an UTF-8 String
     */
    static public String toString(byte[] bytes) {
        // Arrays.toString(bytes)
        return new String(bytes, StandardCharsets.UTF_8);
    }

    /**
     * @return a random generated byte array of length
     */
    static public byte[] getRandomBytes(int length) {
        byte[] bytes = new byte[length];
        new Random().nextBytes(bytes);
        return bytes;
    }


    public static boolean equals(byte[] bytes1, byte[] bytes2) {
        if (bytes1.length != bytes2.length) {
            return false;
        }
        for (int i = 0; i < bytes1.length; i++) {
            if (bytes1[i] != bytes2[i]) {
                return false;
            }
        }
        return true;
    }
}
