package net.bytle.tower.eraldy.app.combopublicapi.openapi.invoker;

import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.openapi.RouterBuilder;
import net.bytle.tower.eraldy.app.combopublicapi.implementer.*;
import net.bytle.tower.eraldy.app.combopublicapi.openapi.interfaces.*;
import net.bytle.vertx.RoutingContextWrapper;

import java.util.function.Function;


/**
* This file is generated by the openApi generator
* via the template `ApiMount.mustache`
* Modify the template if needed
* If you want to modify the package, modify also the
* config file: `.openapi-generator-xxxx-config.yaml`
*/
public class ApiVertxSupport {



private final static AnalyticsPublicapiHandler analyticsHandler = new AnalyticsPublicapiHandler(new AnalyticsPublicapiImpl());

private final static AppPublicapiHandler appHandler = new AppPublicapiHandler(new AppPublicapiImpl());

private final static CspPublicapiHandler cspHandler = new CspPublicapiHandler(new CspPublicapiImpl());

private final static HealthPublicapiHandler healthHandler = new HealthPublicapiHandler(new HealthPublicapiImpl());

private final static ListPublicapiHandler listHandler = new ListPublicapiHandler(new ListPublicapiImpl());

private final static RealmPublicapiHandler realmHandler = new RealmPublicapiHandler(new RealmPublicapiImpl());

private final static RegistrationPublicapiHandler registrationHandler = new RegistrationPublicapiHandler(new RegistrationPublicapiImpl());

private final static UserPublicapiHandler userHandler = new UserPublicapiHandler(new UserPublicapiImpl());


  public static void mount(RouterBuilder builder) {

    analyticsHandler.mount(builder);
    appHandler.mount(builder);
    cspHandler.mount(builder);
    healthHandler.mount(builder);
    listHandler.mount(builder);
    realmHandler.mount(builder);
    registrationHandler.mount(builder);
    userHandler.mount(builder);

  }

  /**
  * See {@link io.vertx.ext.web.Route#respond(Function)}
  */
  public static void respond(RoutingContext ctx, ApiResponse<?> apiResponse) {

    Object data = apiResponse.getData();
    RoutingContextWrapper.createFrom(ctx)
      .respond(data);

  }

}
