# docker-entrypoint.sh is need for db init
# https://github.com/docker-library/postgres/blob/d08757ccb56ee047efd76c41dbc148e2e2c4f68f/16/bookworm/docker-entrypoint.sh
postgres: docker-entrypoint.sh postgres -c config_file=/etc/postgresql/postgresql.conf
postgres_exporter: postgres_exporter --log.level=warn
