package net.bytle.type;

import java.nio.charset.StandardCharsets;
import java.util.Random;



public class Bytes {


    /**
     * hexadecimal digits
     */
    private final static char[] hexArray = "0123456789ABCDEF".toCharArray();

    static public String toHexaDecimalViaStringBuilder(byte[] bytes){
        StringBuilder stringBuilder = new StringBuilder();
        for (byte b : bytes) {
            stringBuilder.append(String.format("%02X", b));
        }
        return stringBuilder.toString();
    }

    // hexadecimal representation of the binary data.
    // hexlify
    // https://stackoverflow.com/questions/9655181/how-to-convert-a-byte-array-to-a-hex-string-in-java
    static public String toHexaDecimalViaMap(byte[] bytes){

        char[] hexChars = new char[bytes.length * 2];
        for ( int j = 0; j < bytes.length; j++ ) {
            int v = bytes[j] & 0xFF;
            hexChars[j * 2] = hexArray[v >>> 4];
            hexChars[j * 2 + 1] = hexArray[v & 0x0F];
        }
        return new String(hexChars);

    }

    static public String toHexaDecimalViaJavaxXml(byte[] bytes){

        return javax.xml.bind.DatatypeConverter.printHexBinary(bytes);

    }

    /**
     * Byte to UTF-8 String
     * @param bytes
     * @return an UTF-8 String
     */
    static public String getString(byte[] bytes){
        String s = new String(bytes, StandardCharsets.UTF_8);
        // Arrays.toString(bytes)
        return s;
    }

    /**
     *
     * @param length
     * @return a random generated byte array of length
     */
    static public byte[] getRandomBytes(int length){
        byte[] bytes = new byte[length];
        new Random().nextBytes(bytes);
        return bytes;
    }

}
