openapi: 3.0.3
info:
  title: Eraldy API
  description: |
    The eraldy api
  # Quote are deleted https://github.com/OpenAPITools/openapi-generator/issues/3196
  # We can't therefore use a date string as the generated openapi.yaml file has no quote
  # and the data is seen as date, not as string
  version: "v2023-06-18"
servers:
  - url: 'https://api.eraldy.com'
# check the openApi.md file to know more about tags.
tags:
  - name: env
    description: Env data
  - name: realm
    description: Operations on realm
  - name: user
    description: Operations about users
  - name: list
    description: Operations about list management (creation, registration)
  - name: app
    description: Operations on app
  - name: registration
    description: Operations on list registration
  - name: analytics
    description: Analytics operation
  - name: token
    description: Public API Token creation
# Secure by default, if you want to make an operation public,
# you need to set the security for an operation to the empty array
# security: []
security:
  # Listed in the openapi-common.yaml
  - apiKeyAuth: [ ]
  - cookieAuth: [ ]
components:
  securitySchemes:
#    cookieAuth: # binding name (arbitrary name used in code and in the file)
#      $ref: './eraldy-common-openapi.yaml#/components/securitySchemes/cookieAuth'
    apiKeyAuth: # binding name (arbitrary name used in code and in the file)
      $ref: './eraldy-common-openapi.yaml#/components/securitySchemes/apiKeyAuth'
    bearerAuth: # binding name (arbitrary name used in code and in the file)
      $ref: './eraldy-common-openapi.yaml#/components/securitySchemes/bearerAuth'
paths:
  /auth/logout:
    get:
      operationId: "authLogoutGet"
      summary: The logout endpoint
      tags:
        - auth
  /auth/login/oauth/{provider}:
    get:
      operationId: "authLoginOauthProviderGet"
      summary: |
        Redirect to the external oauth authorization end point
      tags:
        - auth
  /auth/login/email:
    post:
      operationId: "authLoginEmailPost"
      summary: Login by sending an email with a login link
      tags:
        - auth
      security: [ ]
  /auth/login/oauth/access_token:
    get:
      operationId: "authLoginOauthAccessTokenGet"
      summary: Exchange a code for an access token
      tags:
        - auth
  /auth/login/password:
    post:
      operationId: "authLoginPasswordPost"
      # even if the request does not change anything, this is a post
      # GitHub does it also this way
      # The Csrf token is passed via HTTP headers
      summary: The login form end point for password credentials
      tags:
        - auth
      security: [ ]
  /auth/login/password/update:
    post:
      operationId: "authLoginPasswordUpdatePost"
      summary: "Update the password"
      tags:
        - auth
  /auth/login/password/reset:
    post:
      operationId: "authLoginPasswordResetPost"
      summary: "Login via a link and give the possibility to modify the password"
      tags:
        - auth
      security: [ ]
  /auth/user/register:
    post:
      operationId: "authUserRegisterPost"
      summary: "Register a user"
      tags:
        - auth
      security: [ ]
  /analytics/event:
    post:
      operationId: analyticsEventPost
      summary: "Report a analytics event"
      security: [ ]
      tags:
        - analytics
  /csp/report:
    post:
      operationId: cspReportPost
      # https://w3c.github.io/webappsec-csp/#cspviolationreportbody
      summary: "Report a CSP Violation"
      security: [ ]
      tags:
        - csp
  /env:
    get:
      operationId: "envGet"
      summary: Return environment data
      tags:
        - env
  /ping:
    get:
      operationId: "pingGet"
      summary: A health check endpoint
      # tag is the prefix of the API
      security: [ ]
      tags:
        - health
  # A realm is a container/scope for a user login
  # A realm may have several apps where the user can log in
  # with the same credential
  # We don't use domain because it has strong web connotation
  # (note there is 197,046,670 domain active, 1,139,467,659 registered)
  /realm:
    get:
      operationId: "realmGet"
      summary: "Return the asked realm"
      tags:
        - realm
    post:
      operationId: "realmPost"
      summary: "Create a realm"
      tags:
        - realm
      security:
        - apiKeyAuth: [ 'write:realm' ]
  /realms:
    get:
      operationId: "realmsGet"
      summary: "Return the list of realms"
      tags:
        - realm
      security:
        - apiKeyAuth: [ 'read:realm' ]
  /realms/owned-by/{userGuid}:
    get:
      operationId: "realmsOwnedByGet"
      summary: "Return the list of realms owned by the user"
      tags:
        - realm
      security:
        - apiKeyAuth: [ 'read:realm' ]
  /realms/owned-by/me:
    get:
      operationId: "realmsOwnedByMeGet"
      summary: "Return the list of realms owned by the authenticated user"
      tags:
        - realm
      security:
        - apiKeyAuth: [ 'read:realm' ]
  /realm/{realmGuid}/users/new:
    get:
      operationId: "realmUsersNewGet"
      summary: "Return the list of recent new users for the realm"
      tags:
        - realm
      security:
        - apiKeyAuth: [ 'read:realm' ]
  /services:
    get:
      operationId: servicesGet
      summary: "Get all services"
      tags:
        - service
      security:
        - apiKeyAuth: [ 'read:service' ]
  /campaign/email:
    post:
      operationId: campaignEmailPost
      summary: "Create an email campaign"
      tags:
        - campaign
      security:
        - apiKeyAuth: [ 'write:campaign' ]
  /service:
    get:
      operationId: serviceGet
      summary: "Retrieve a service by guid or uri"
      tags:
        - service
      security:
        - apiKeyAuth: [ 'read:service' ]
  /service/smtp:
    post:
      operationId: serviceSmtpPost
      summary: "Create a SMTP mail service for a app or a user"
      tags:
        - service
      security:
        - apiKeyAuth: [ 'write:service' ]
  /app:
    post:
      operationId: appPost
      summary: "Create or modify an app (ie design, ...)"
      tags:
        - app
      security:
        - apiKeyAuth: [ 'write:app' ]
    get:
      operationId: appGet
      summary: |
        Retrieve an app by:
        * id with the appGuid
        * or by name with the appUri and realm (Handle or Guid)
      tags:
        - app
      security:
        - apiKeyAuth: [ 'read:app' ]
  /apps:
    get:
      operationId: appsGet
      summary: "List apps for a realm"
      tags:
        - app
      security:
        - apiKeyAuth: [ 'read:app' ]
  /user/auth:
    get:
      operationId: userAuthGet
      summary: Return the authenticated user
      tags:
        - user
  /user:
    get:
      operationId: userGet
      summary: |
        Get a user by guid or email
      tags:
        - user
      security:
        - apiKeyAuth: [ 'read:user' ]
    post:
      operationId: userPost
      summary: "Create or modify a user (a guid or a email should be given)"
      tags:
        - user
      security:
        - apiKeyAuth: [ 'write:user' ]
  /user/me:
    get:
      operationId: "userMeGet"
      summary: "Get the authenticated user"
      tags:
        - user
      security: [ ]
  /user/{guid}:
    get:
      operationId: userGuidGet
      # The parameter is guid and not an email because @ is a special URL character
      # and the openApi router will then not find the route (resource not found)
      summary: |
        Get a user by guid

        If you want to use the email has identifier,
        you should use the `userGet` operation passing the email as query parameter
      tags:
        - user
      security:
        - apiKeyAuth: [ 'read:user' ]
  /users:
    get:
      operationId: usersGet
      summary: "List users"
      tags:
        - user
      security:
        - apiKeyAuth: [ 'read:user' ]
  /list:
    get:
      operationId: listGet
      summary: |
        Get list information

        Access by:
        * id with the listGuid
        * name with the listHandle and realmHandle
      tags:
        - list
      security:
        - apiKeyAuth: [ 'write:read' ]
    post:
      operationId: listPost
      summary: "Create a list where users can register"
      tags:
        - list
      security:
        - apiKeyAuth: [ 'write:list' ]
  /lists:
    get:
      operationId: listsGet
      summary: |
        Get a list of lists

        The app should be given via:
          - the appGuid
          - or the appUri along with the realmGuid or realmHandle
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]
#            format: uri - format is not supported for parameters
        - name: realmGuid
          description: "The realm Guid"
          in: query
          schema:
            type: string
        - name: realmHandle
          description: "The realm Handle"
          in: query
          schema:
            type: string
  /lists/summary:
    get:
      operationId: listsSummaryGet
      summary: "Get a list of list in a summary format"
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]
  /list/registration:
    get:
      operationId: listRegistrationGet
      summary: "Get a registration object"
      description: |
        Get a registration
          * by id with the registrationGuid
          * by name with the subscriberEmail and listGuid
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]
  /list/registration/validation:
    get:
      operationId: listRegistrationValidationGet
      summary: |
        The URI of the validation link in the validation
        letter that the user receive.
        The user needs to click this link to confirm her/his registration.
      tags:
        - list
      security: [ ]
  /list/registration/letter/confirmation:
    get:
      operationId: listRegistrationLetterConfirmationGet
      summary: |
        Return the confirmation letter after the user has clicked on the validation link.

        To get a confirmation as it's show to a user, you just need to set
        the subscriber name and the list guid

        The other parameters will overwrite other list information.
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]
  /list/registration/letter/validation:
    get:
      operationId: listRegistrationLetterValidationGet
      summary: |
        Return the validation letter with a validation link as send by email.
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]
  /list/register:
    post:
      operationId: listRegisterPost
      summary: "Register a user to a list by sending an email for validation"
      tags:
        - list
      security: [ ]
  # callback
  /list/register/confirmation/{registration_guid}:
    get:
      operationId: "listRegisterConfirmationRegistrationGet"
      summary: "Shows a confirmation page for the registration"
      tags:
        - list
      security: [ ]
  /list/registrations:
    get:
      operationId: listRegistrationsGet
      summary: "List the registrations for a list"
      tags:
        - list
      security:
        - apiKeyAuth: [ 'read:list' ]