package net.bytle.tower.eraldy.app.comboprivateapi.openapi.invoker;

import io.vertx.core.buffer.Buffer;
import io.vertx.core.http.HttpHeaders;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.HttpException;
import io.vertx.ext.web.openapi.RouterBuilder;
import net.bytle.tower.eraldy.app.comboprivateapi.implementer.*;
import net.bytle.tower.eraldy.app.comboprivateapi.openapi.interfaces.*;

import java.util.function.Function;


/**
* This file is generated by the openApi generator
* via the template `ApiMount.mustache`
* Modify the template if needed
* If you want to modify the package, modify also the
* config file: `.openapi-generator-xxxx-config.yaml`
*/
public class ApiVertxSupport {



private final static AppComboprivateapiHandler appHandler = new AppComboprivateapiHandler(new AppComboprivateapiImpl());

private final static CampaignComboprivateapiHandler campaignHandler = new CampaignComboprivateapiHandler(new CampaignComboprivateapiImpl());

private final static EnvComboprivateapiHandler envHandler = new EnvComboprivateapiHandler(new EnvComboprivateapiImpl());

private final static HealthComboprivateapiHandler healthHandler = new HealthComboprivateapiHandler(new HealthComboprivateapiImpl());

private final static ListComboprivateapiHandler listHandler = new ListComboprivateapiHandler(new ListComboprivateapiImpl());

private final static RealmComboprivateapiHandler realmHandler = new RealmComboprivateapiHandler(new RealmComboprivateapiImpl());

private final static RegistrationComboprivateapiHandler registrationHandler = new RegistrationComboprivateapiHandler(new RegistrationComboprivateapiImpl());

private final static ServiceComboprivateapiHandler serviceHandler = new ServiceComboprivateapiHandler(new ServiceComboprivateapiImpl());

private final static UserComboprivateapiHandler userHandler = new UserComboprivateapiHandler(new UserComboprivateapiImpl());


  public static void mount(RouterBuilder builder) {

    appHandler.mount(builder);
    campaignHandler.mount(builder);
    envHandler.mount(builder);
    healthHandler.mount(builder);
    listHandler.mount(builder);
    realmHandler.mount(builder);
    registrationHandler.mount(builder);
    serviceHandler.mount(builder);
    userHandler.mount(builder);

  }

  /**
  * See {@link io.vertx.ext.web.Route#respond(Function)}
  */
  public static void respond(RoutingContext ctx, ApiResponse<?> apiResponse) {

    /**
    * Future.succeededFuture() does not trigger a type error
    */
    if (apiResponse == null) {
      apiResponse = new ApiResponse<>();
    }

    Object data = apiResponse.getData();
    if (ctx.response().headWritten()) {
      if (data == null) {
        if (!ctx.response().ended()) {
          ctx.end();
        }
        return;
      }
      ctx.fail(new HttpException(500, "Response already written"));
    }

    if (data == null) {
      int statusCode = apiResponse.getStatusCode();
      if (statusCode == 200) {
        statusCode = 204;  // No Content success status response
      }
      ctx.response()
         .setStatusCode(statusCode)
         .end();
      return;
    }

    final boolean hasContentType = ctx.response().headers().contains(HttpHeaders.CONTENT_TYPE);
    if (data instanceof Buffer) {
      if (!hasContentType) {
        ctx.response().putHeader(HttpHeaders.CONTENT_TYPE, "application/octet-stream");
      }
      ctx.end((Buffer) data);
      return;
    }

    if (data instanceof String) {
      if (!hasContentType) {
        ctx.response().putHeader(HttpHeaders.CONTENT_TYPE, "text/html");
      }
      ctx.end((String) data);
      return;
    }

    ctx.json(data);

  }

}
