
# as env or in secret file
# the token to access the token
# api.token.cloudflare: xxx


# Number of days before an expiration error is issued
api.token.days.before.expiration.failure: 30

# smtp
mail.smtp.default.hostname: localhost
mail.smtp.default.port: 25
mail.smtp.default.username: 'nico@bytle.net'
mail.smtp.default.sender: nico@bytle.net
# see also in secret
# mail.smtp.default.password
