
# as env or in secret file
# the token to access the token
# api.token.cloudflare: xxx

# Number of days before an expiration error is issued
api.token.days.before.expiration.failure: 30

# smtp
mail.smtp.default.hostname: smtp.gmail.com
mail.smtp.default.port: 465
mail.smtp.default.username: 'nico@eraldy.com'
mail.smtp.default.sender: nico@eraldy.com
# see also in secret
# mail.smtp.default.password
# mail.smtp.default.username: 'nico@bytle.net'
