
# as env or in secret file
# the token to access the token
# api.token.cloudflare: xxx


# Number of days before an expiration error is issued
api.token.days.before.expiration.failure: 30

# smtp
mail.smtp.default.hostname: localhost
mail.smtp.default.port: 25
mail.smtp.default.sender: nico@eraldy.com
# mail.smtp.default.username: 'nico@bytle.net'
# see also in secret
# mail.smtp.default.password

# Monitor key created
# thanks to https://help.ovhcloud.com/csm/en-gb-api-getting-started-ovhcloud-api
ovh.monitoring.endpoint: ovh-eu
# as env in the secret file
#ovh.application.key: my_app_key
#ovh.application.secret: my_application_secret
#ovh.consumer.key: my_consumer_key
