package com.tabulify.fs.textfile;

import java.util.HashMap;
import java.util.Map;

public class FsTextExtensions {

  static public Map<String,String> textExtensions = new HashMap<>();

  static {
    textExtensions.put("!!!","README text");
    textExtensions.put("$00 $00","MS-DOS pipe data");
    textExtensions.put("$01 $01","MS-DOS pipe file");
    textExtensions.put("$02 $02","MS-DOS pipe");
    textExtensions.put("$04 $04","MS-DOS pipe");
    textExtensions.put("$05 $05","MS-DOS pipe file");
    textExtensions.put("$o1 $o1","MS-DOS pipe");
    textExtensions.put("$ol $ol","MS-DOS pipe");
    textExtensions.put("001","SwiftView ICS command data");
    textExtensions.put("1","Unix unformatted manual page");
    textExtensions.put("1st","Readme first text document");
    textExtensions.put("7","GNU Screen log");
    textExtensions.put("8","Unix unformatted manual page");
    textExtensions.put("82t","TI-82 text");
    textExtensions.put("89t","TI-89 text");
    textExtensions.put("92t","TI-92 text");
    textExtensions.put("9xt","TI-89 text");
    textExtensions.put("_me","Read me file");
    textExtensions.put("abt","Braille2000 annotated braille text");
    textExtensions.put("ac","AC3D geometry data");
    textExtensions.put("adiumhtmllog adiumhtmllog","Adium HTML log");
    textExtensions.put("adiumlog adiumlog","Adium log");
    textExtensions.put("adl","ADONIS models and model groups export");
    textExtensions.put("adoc","Asciidoctor document");
    textExtensions.put("adt adt","AutoCAD audit report");
    textExtensions.put("adw","Tamil transliterater/font converter data");
    textExtensions.put("alx","BlackBerry application loader");
    textExtensions.put("aml aml","Microsoft Assistance Markup Language");
    textExtensions.put("android","Readme file");
    textExtensions.put("annot annot","Adobe Digital Editions annotations data");
    textExtensions.put("ans","ANSI text (ANSI Art)");
    textExtensions.put("ansi","Mistaken TXT document");
    textExtensions.put("application","ClickOnce deployment manifest");
    textExtensions.put("aprj","ApacheConf project");
    textExtensions.put("apx","ArcPad XML document");
    textExtensions.put("aqt","AQTitle subtitles");
    textExtensions.put("arff","Weka attribute-relation data");
    textExtensions.put("artask","Remedy User Tool shortcut");
    textExtensions.put("asc","ASCII text");
    textExtensions.put("ascii","ASCII text characters data");
    textExtensions.put("asl","AppSight console log");
    textExtensions.put("asp","ASP text document");
    textExtensions.put("asp","Active Server Page script page");
    textExtensions.put("ass","Advanced SubStation Alpha subtitles");
    textExtensions.put("assoc","Associate This file association database file");
    textExtensions.put("att","Web Form Data");
    textExtensions.put("awa","ActiveWords data");
    textExtensions.put("awb","ActiveWords WordBase file");
    textExtensions.put("awh","ActiveWorlds browser help data");
    textExtensions.put("axt","ASCII Application Object template");
    textExtensions.put("ba1 ba1","Microsoft Windows Media Center report log");
    textExtensions.put("bad","Microsoft Exchange badmail data");
    textExtensions.put("bas","Basic source code");
    textExtensions.put("bbs","Bulletin Board System text document");
    textExtensions.put("bcr","map&guide station list");
    textExtensions.put("bdn","Blu-ray BDN XML subtitle data");
    textExtensions.put("bdp","Microsoft Exchange diagnostic message");
    textExtensions.put("bea","Beamer song file");
    textExtensions.put("bel","Beamer layout data");
    textExtensions.put("bep","Beamer playlist file");
    textExtensions.put("big","Chinese text");
    textExtensions.put("big5","Chinese text");
    textExtensions.put("bk","Movie Magic Screenwriter document backup file");
    textExtensions.put("blm","Eurolink comma separated value");
    textExtensions.put("bln","Golden Software Blanking file format");
    textExtensions.put("blw","ArcView world file for bil image");
    textExtensions.put("bna","Atlas Boundary data");
    textExtensions.put("bnx","Board Neutral Exchange data");
    textExtensions.put("bog","Binary object geometry format");
    textExtensions.put("box box","AIM AOL Instant Messenger boxely data");
    textExtensions.put("bpdx bpdx","Adobe Acrobat catalog batch PDX data");
    textExtensions.put("brf brf","Braille ready format");
    textExtensions.put("bsdl","Boundary Scan Description Language");
    textExtensions.put("bss","Bridge Base data");
    textExtensions.put("bt","Binary Template Archive");
    textExtensions.put("bzw","BZFlag map");
    textExtensions.put("cag cag","Capella gallery");
    textExtensions.put("cas","Comma-delimited ASCII document");
    textExtensions.put("cc","Trojan Spymaster.A text document");
    textExtensions.put("cd2","DATAIR Cafeteria Document System custom text");
    textExtensions.put("cdt","ImgBurn CD-text project");
    textExtensions.put("charset","Character set");
    textExtensions.put("cho","CUHP output file");
    textExtensions.put("chord","Song chords");
    textExtensions.put("cif","Caltech Intermediate Format file");
    textExtensions.put("cil","Norton CleanSweep installation log");
    textExtensions.put("ckn","Disk Doctors licence log");
    textExtensions.put("clg clg","QIP list of ignored contacts file");
    textExtensions.put("cli cli","QIP invisible list");
    textExtensions.put("clipping clipping","Mac Text clipping file (prior Mac OS 9)");
    textExtensions.put("clix","CLIX command data");
    textExtensions.put("cm0013","Device identify data file");
    textExtensions.put("cof","AutoDesk data");
    textExtensions.put("conf","Configuration information");
    textExtensions.put("coo","AutoCAD Bounding Coordinates Cookie");
    textExtensions.put("crash crash","Apple Mac Console report");
    textExtensions.put("crd","Guitar chord");
    textExtensions.put("crwl crwl","Microsoft Windows crawl log");
    textExtensions.put("csassembly csassembly","ICQ 6 data");
    textExtensions.put("csmanifest csmanifest","ICQ 6 settings");
    textExtensions.put("csv","Comma Separated Value file");
    textExtensions.put("ctd","CardTable data");
    textExtensions.put("ctf","Casio calculator text format");
    textExtensions.put("ctl","EditPlus cliptext file");
    textExtensions.put("ctl ctl","Visual Basic control data (Active X control data)");
    textExtensions.put("ctx","GE Industrial Systems CIMPLICITY text version HMI screen");
    textExtensions.put("dat","Tecplot ASCII data");
    textExtensions.put("dbt","Database text memo");
    textExtensions.put("dcd","Document Content Description (XML) data");
    textExtensions.put("dce dce","AutoCAD R2000 dialogue error log");
    textExtensions.put("ddd","BullsEye text or style sheet");
    textExtensions.put("de","German language translation");
    textExtensions.put("dea","Drug Enforcement Administration record data");
    textExtensions.put("dectest","Decimal test data");
    textExtensions.put("des","Description text");
    textExtensions.put("desc","Description data");
    textExtensions.put("dfe","RISC OS comma separated value file");
    textExtensions.put("dfm","Delphi Win32 form");
    textExtensions.put("dii","CT Summation document image information load file");
    textExtensions.put("diskdefines","Linux LiveCD information data");
    textExtensions.put("diz","Description in ZIP archive");
    textExtensions.put("dk","Danish text/localization");
    textExtensions.put("dkz","ZIP description text");
    textExtensions.put("dmr","BrainVoyager QX project");
    textExtensions.put("dne","Netica Bayesian network text file");
    textExtensions.put("dok","ASCII text");
    textExtensions.put("dp","Text document");
    textExtensions.put("dpv","PrintView RAW text");
    textExtensions.put("dqy dqy","Microsoft Excel ODBC query");
    textExtensions.put("drp","Droplets data file");
    textExtensions.put("dsc","Tag descriptor data");
    textExtensions.put("dsml","Directory Services Markup Language (DSML) identity feed");
    textExtensions.put("dtd","Document Type Definition format");
    textExtensions.put("ecsv","Encapsulated Comma Separated Value file");
    textExtensions.put("edml edml","EDML Parser-Library file");
    textExtensions.put("efm","Electronic Fiction Manuscript file");
    textExtensions.put("eia","Excellon data");
    textExtensions.put("emulecollection","eMule collection data file");
    textExtensions.put("en","English language localization file");
    textExtensions.put("enc","Encore musical notation file format");
    textExtensions.put("enf","Musitek SmartScore Extended Notation Format");
    textExtensions.put("err","Error log");
    textExtensions.put("es","Spanish language translation data");
    textExtensions.put("etf","Enriched Text Format e-mail message");
    textExtensions.put("etx","Setext Structure Enhanced text");
    textExtensions.put("euc","UNIX japanese text (Kanji)");
    textExtensions.put("ext","E-mail text attachment");
    textExtensions.put("extra extra","Mozilla Firefox crash report");
    textExtensions.put("faq","Frequently Asked Questions");
    textExtensions.put("fff","RISC OS ASCII text");
    textExtensions.put("ffp","FLAC fingerprint data");
    textExtensions.put("fil","File list");
    textExtensions.put("fin","Sapir Torah text");
    textExtensions.put("first","Formatted text");
    textExtensions.put("flr","Flare decompiled ActionScript");
    textExtensions.put("fnx","Fenix Key data");
    textExtensions.put("fon","COREX manually verified broad phonetic transcription data");
    textExtensions.put("fpt","Database memo file");
    textExtensions.put("fr","French language translation");
    textExtensions.put("fra","French localization");
    textExtensions.put("frm","Form file");
    textExtensions.put("fsa","FASTA DNA and Protein Sequence Alignment");
    textExtensions.put("full","Cygwin variable log");
    textExtensions.put("gbf","General Bible Format");
    textExtensions.put("gen","Ventura Publisher generated text data");
    textExtensions.put("ger","German text/html info");
    textExtensions.put("gnu","GNU licence information");
    textExtensions.put("gpl","GNU Public Licence text file");
    textExtensions.put("gthr gthr","Microsoft Exchange Server gather log");
    textExtensions.put("gtx","GX Text word pad data");
    textExtensions.put("guide","AmigaGuide hypertext document");
    textExtensions.put("hdr","ArcView header data");
    textExtensions.put("hhc","HTML Help table of contents");
    textExtensions.put("hhs","Microsoft HTML Help Workshop sample data");
    textExtensions.put("hlm","Help data");
    textExtensions.put("hpm","HP NewWave emm text");
    textExtensions.put("hs","Java HelpSet file");
    textExtensions.put("htm","HTML Hypertext Markup Language web page");
    textExtensions.put("html","HyperText Markup Language web page");
    textExtensions.put("html5","HTML5 Hypertext Markup Language revision 5 source");
    textExtensions.put("htmls","HyperText Markup Language document with server-side include");
    textExtensions.put("htx","Microsoft FrontPage database results");
    textExtensions.put("hvc","ASCII text");
    textExtensions.put("hz","Chinese (Hanzi) text");
    textExtensions.put("idc","Text document");
    textExtensions.put("idt","Windows Installer exported database table");
    textExtensions.put("idx","Easy Timesheets data");
    textExtensions.put("iem","Informix error message");
    textExtensions.put("igtx","IGOR Pro text document");
    textExtensions.put("igv","Integrative Genomics Viewer data");
    textExtensions.put("igy","Microsoft Excel web query data");
    textExtensions.put("iif","QuickBooks interchange format");
    textExtensions.put("ill","Illust Logic Puzzle data");
    textExtensions.put("inc","JAWS text file");
    textExtensions.put("inc inc","Pascal file");
    textExtensions.put("inuse","Text configuration (in use)");
    textExtensions.put("ion","Description data / Mascot data");
    textExtensions.put("ipr","IntelliJ project XML data");
    textExtensions.put("isr","InstallShield uninstall information data");
    textExtensions.put("it","Italian language translation file");
    textExtensions.put("ja","Japanese language translation");
    textExtensions.put("jam","Altera ASCII text / Jam music score / JAM Message Base format");
    textExtensions.put("jeb","PENSIM output");
    textExtensions.put("jis","Japanese Industry Standard text");
    textExtensions.put("jp1","Japanese (Romaji) text file");
    textExtensions.put("jss","JACOSub subtitles");
    textExtensions.put("jtx","Jrju text data");
    textExtensions.put("kahl","Think Pascal KAHL text data");
    textExtensions.put("kar","MIDI Karaoke song");
    textExtensions.put("kch","KChess notation data");
    textExtensions.put("kix","KiXtart script");
    textExtensions.put("klg","Log file");
    textExtensions.put("kor","Korean localization language data");
    textExtensions.put("la","GNU Libtool library file");
    textExtensions.put("label","Label");
    textExtensions.put("las","LAS Log ASCII standard file format");
    textExtensions.put("lay","Rhino 3D layer text");
    textExtensions.put("ldf","Microsoft SQL Server log");
    textExtensions.put("lin","Bridge Base file");
    textExtensions.put("linux","Linux data");
    textExtensions.put("linx","Bridge base data");
    textExtensions.put("lisp lisp","LISP translators file");
    textExtensions.put("lnc","Football Manager player data");
    textExtensions.put("lo_","Microsoft System Management Server renamed old log");
    textExtensions.put("log","Log");
    textExtensions.put("lrc","Lyrics data");
    textExtensions.put("lst","Family Tree Maker error log / List text / Ingres dump list file / Adobe Type Manager font list / Microsoft PowerPoint playlist / Microsoft Visual FoxPro Documenting Wizard list file");
    textExtensions.put("ltr","Letter document");
    textExtensions.put("ltt","HP Library and Tape Tools log");
    textExtensions.put("ltx","S.T.A.L.K.E.R. game settings");
    textExtensions.put("lue","Norton LiveUpdate log");
    textExtensions.put("luf","Lipikar Uniform Format file");
    textExtensions.put("lwd","LotusWorks text document");
    textExtensions.put("lxfml","LEGO Digital Designer XML data");
    textExtensions.put("lyr","Lyrics");
    textExtensions.put("lyt lyt","TurboTax install log");
    textExtensions.put("man","Unix text manual");
    textExtensions.put("manifest","Manifest data");
    textExtensions.put("map","Offline Explorer data");
    textExtensions.put("map map","Microsoft Visual Studio Linker map");
    textExtensions.put("mar","MARC 21 bibliographic data");
    textExtensions.put("markdown","Markdown markup language source code");
    textExtensions.put("mathml","Mathematical Markup Language document");
    textExtensions.put("maxfr","MaxView web pointer data");
    textExtensions.put("mcw","MacWrite II text document");
    textExtensions.put("md","Markdown markup language source code");
    textExtensions.put("mdle","Motion Description Language Extended data");
    textExtensions.put("mdown","Markdown markup language source code");
    textExtensions.put("mdtext","Markdown markup language source code");
    textExtensions.put("mdtxt","Markdown markup language source code");
    textExtensions.put("mdwn","Markdown markup language");
    textExtensions.put("me","Readme text");
    textExtensions.put("mez","RealArcade game information");
    textExtensions.put("mf","Metafont text font");
    textExtensions.put("mib","Management Information Base data");
    textExtensions.put("mit","MineEdit inventory template");
    textExtensions.put("mkd","Markdown markup language source code");
    textExtensions.put("mkdn","Markdown markup language source file");
    textExtensions.put("modd","Picture Motion Browser data");
    textExtensions.put("mp3","Masterpoint green points data");
    textExtensions.put("mpl","MPL2 subtitles");
    textExtensions.put("mss","Manuscript text");
    textExtensions.put("mtx","Anjal Murasu tamil text file / Microsoft Visual Studio manual test text");
    textExtensions.put("mtxt","MOPEKS problem data");
    textExtensions.put("mw","MediaWiki structured text file");
    textExtensions.put("nbr","NovaBench saved benchmark result");
    textExtensions.put("nclk","HTML formatted text");
    textExtensions.put("new","New information data");
    textExtensions.put("nfo","Information readme text document");
    textExtensions.put("nlc","Nero Linux compilation");
    textExtensions.put("nmbd","Samba log file");
    textExtensions.put("nna","NeuralWare data");
    textExtensions.put("nokogiri","Nokogiri source data");
    textExtensions.put("not","Notation or note");
    textExtensions.put("notes","Memento note");
    textExtensions.put("now","Text file");
    textExtensions.put("nt","Windows NT command script");
    textExtensions.put("nwctxt","NoteWorthy Composer text");
    textExtensions.put("ocr","FaxGrapper FAX transcribed text");
    textExtensions.put("odc","Microsoft Office database connection data");
    textExtensions.put("oh","DrillAssistant list");
    textExtensions.put("ojp","3WayPack data");
    textExtensions.put("omn","Omnipotent collection data");
    textExtensions.put("oogl","Geomview Object Oriented Graphics Library");
    textExtensions.put("oot","Apache OpenOffice (OpneOffice.org) text document");
    textExtensions.put("opc","Microsoft Office 97 upgrade control data");
    textExtensions.put("openbsd","OpenBSD readme document");
    textExtensions.put("opml","OPML Outline Processor Markup Language file format");
    textExtensions.put("ort","IBM Lotus Quickr Rich Text Editor document");
    textExtensions.put("osi","SunNet OSI description");
    textExtensions.put("osn","Open Symbolic Notation data");
    textExtensions.put("p3x","HTML document");
    textExtensions.put("pac","Polistream video subtitle data");
    textExtensions.put("panic","Apple Mac OS X Console panic report");
    textExtensions.put("pc5","Rockwell Software Logix 5 internal data");
    textExtensions.put("pcc","Photocomposition codes");
    textExtensions.put("pcl pcl","HP vector graphics");
    textExtensions.put("pd","Pure Data patchfile");
    textExtensions.put("pdu","Protocol data unit message");
    textExtensions.put("pfs","pfs:Write text");
    textExtensions.put("pgw","Map data");
    textExtensions.put("phr","Adobe RoboHelp phrase");
    textExtensions.put("pjs","Phoenix Japanimation Society subtitle");
    textExtensions.put("pl","Perl script language source code");
    textExtensions.put("pla","iriver iQuickList playlist file");
    textExtensions.put("plf","SalesLogix pick list text");
    textExtensions.put("plist","Apple property XML list");
    textExtensions.put("plk","COREX part-of-speech tag");
    textExtensions.put("pln","Microsoft Flight Simulator flight plan");
    textExtensions.put("pmo","Pegasus Mail saved message");
    textExtensions.put("pod","Perl POD-formated text");
    textExtensions.put("prc","Palm OS resource or e-book");
    textExtensions.put("prn","Lotus 1-2-3 formatted text");
    textExtensions.put("pro","COREX prosodic annotation");
    textExtensions.put("prr","Accent OFFICE Password Recovery file");
    textExtensions.put("psb","PowerDivX subtitles file");
    textExtensions.put("pt3","Protext formatted text data file");
    textExtensions.put("pvj","ProofVision job ticket file");
    textExtensions.put("pvw","Portfolio saved view");
    textExtensions.put("q&a","Questions and answers document");
    textExtensions.put("qdt","QuarkXpress auxiliary dictionary file");
    textExtensions.put("qud","QuarkXpress auxiliary dictionary file");
    textExtensions.put("rdf","Resource Description Framework RSS feed");
    textExtensions.put("rea","readme text file");
    textExtensions.put("readme","README text document");
    textExtensions.put("reg","Windows registry data");
    textExtensions.put("report","Report");
    textExtensions.put("resp","Microsoft Windows report log");
    textExtensions.put("rest","reStructuredText data");
    textExtensions.put("rff","Roproc Format");
    textExtensions.put("ris","Research Information Systems citation");
    textExtensions.put("rml","Redline Markup Language source");
    textExtensions.put("rst","reStructuredText data");
    textExtensions.put("rt","Rich Text document");
    textExtensions.put("rtf","Rich Text Format document");
    textExtensions.put("rtl","Text file");
    textExtensions.put("rtx","Rich Text document");
    textExtensions.put("ru","Russian text or localization file");
    textExtensions.put("rus","Russian text or localization data");
    textExtensions.put("rzn","Red Zion E-book notes");
    textExtensions.put("s19","Motorola EEPROM programming data");
    textExtensions.put("s2k","Sasami2K Subtitle file");
    textExtensions.put("s2s","SRT2SUP native subtitle format");
    textExtensions.put("sami","Synchronized Accessible Media Interchange file format");
    textExtensions.put("sbv","YouTube captions data");
    textExtensions.put("sdnf","Steel Detailing Neutral File Format");
    textExtensions.put("sen","SenTest test results");
    textExtensions.put("seq","Commodore text");
    textExtensions.put("set","3WayPack data");
    textExtensions.put("sfb","Sony Playstation 3 game disc description data");
    textExtensions.put("sha1","SHA-1 text hash");
    textExtensions.put("sha512","SHA512 hash");
    textExtensions.put("sk","Slovak language translation");
    textExtensions.put("skcard","Borland Sidekick contact");
    textExtensions.put("skv","Semicolon separated values file");
    textExtensions.put("smali","Google Android Smali Assembly Language developer data");
    textExtensions.put("smf","System Monitor session");
    textExtensions.put("smi","Microsoft SAMI subtitles");
    textExtensions.put("sms","Sony Ericsson exported SMS file");
    textExtensions.put("snw","Sweave source data");
    textExtensions.put("soap","Simple Object Access Protocol Message (SOAP) message");
    textExtensions.put("soundscript","Rigs of Rods sound script description");
    textExtensions.put("spec","Specification data");
    textExtensions.put("spg","MOIRA text file");
    textExtensions.put("spn","Spanish readme data");
    textExtensions.put("spx","Apple System Profiler computer information data");
    textExtensions.put("srt","WebSRT movie subtitle file format / SubRip video subtitle format");
    textExtensions.put("srx","SPARQL Query Results XML format result");
    textExtensions.put("ssa","SubStation Alpha subtitle data");
    textExtensions.put("ssf","Subtitles");
    textExtensions.put("st1","DigiTitle Master subtitle");
    textExtensions.put("stq","StatSoft Statistica text");
    textExtensions.put("strings","Apple Mac strings");
    textExtensions.put("sub","DivX movie subtitle file format");
    textExtensions.put("t","Microsoft Windows Notepad text");
    textExtensions.put("t2t","Txt2tags text document file");
    textExtensions.put("tab","Tab separated value / Guitar tablature");
    textExtensions.put("tbd","Dansk System Industr text");
    textExtensions.put("tbl","Table data");
    textExtensions.put("tce","TLE File Format");
    textExtensions.put("tcm","INMOS Transputer Development System Occam comment text");
    textExtensions.put("tdf","Project Pluto Guide text definition data");
    textExtensions.put("tdump","JIRA thread dump");
    textExtensions.put("ted","DVICO Tvix log");
    textExtensions.put("text","Simple text file");
    textExtensions.put("textclipping","Mac Text clipping file (after Mac OS 9)");
    textExtensions.put("textile","Eclipse IDE WikiText document");
    textExtensions.put("tfw","ArcView world data");
    textExtensions.put("tgf","Trival Graph Format");
    textExtensions.put("thp","TurboTax text string file");
    textExtensions.put("tlb","VAX text library");
    textExtensions.put("tle","TLE File Format file");
    textExtensions.put("tlx","Technics Sx KN 6000 keyboard text lyrics / Wintertree spell-checking dictionaries");
    textExtensions.put("tm","TeXmacs document");
    textExtensions.put("tmprtf","TimeMap portable file format");
    textExtensions.put("tmx","Translation memory eXchange data");
    textExtensions.put("tnef","Transport neutral encapsulation format file");
    textExtensions.put("tph","Turbo Pascal help data");
    textExtensions.put("tpl","TNTedit text template");
    textExtensions.put("trn","STN Express transcript text");
    textExtensions.put("trt","DLocalizer translations file");
    textExtensions.put("tsv","Tab Separated Values");
    textExtensions.put("tt","Microsoft Visual Studio text template");
    textExtensions.put("ttbl","TTPlayer play list");
    textExtensions.put("tte","TextTransformer remodeled text");
    textExtensions.put("ttf","Quartus II tabular text");
    textExtensions.put("ttpl","TTPlayer play list");
    textExtensions.put("ttxt","Apple SimpleText data");
    textExtensions.put("tx8","8-bit DOS ASCII text");
    textExtensions.put("tx?","LoseThos text document");
    textExtensions.put("txa","Clarion exported to text format");
    textExtensions.put("txd","Clarion for Windows application code in text format");
    textExtensions.put("txe","Enriched text file");
    textExtensions.put("txh","Light markup language text file");
    textExtensions.put("txk","Karaoke song lyrics");
    textExtensions.put("txt","Simple text");
    textExtensions.put("txt txt","Ascii text parameter description data");
    textExtensions.put("u3i","U3 application information file");
    textExtensions.put("uhtml","uHTML document");
    textExtensions.put("uk","English (British) language translation");
    textExtensions.put("unauth","SiteMinder unauthorized message");
    textExtensions.put("uni","Unicode text");
    textExtensions.put("unx","Unix readme document");
    textExtensions.put("us","English language translation file");
    textExtensions.put("user","Microsoft Visual Studio project user options");
    textExtensions.put("usf","Core Media Player XML universal subtitle format");
    textExtensions.put("usg","PC-Doctor for Windows data");
    textExtensions.put("utf8","Unicode UTF-8 encoded text");
    textExtensions.put("utx","Unicode file");
    textExtensions.put("utxt","Unicode text");
    textExtensions.put("v2t","Voyage200 text");
    textExtensions.put("vcf","Variant Call Format");
    textExtensions.put("ver ver","Version description");
    textExtensions.put("vers","Version description data");
    textExtensions.put("vfk","Czech Cadastral Exchange Data Format");
    textExtensions.put("vhd","Quartus II VHDL design data");
    textExtensions.put("vhdl","Quartus II VHDL design");
    textExtensions.put("vis","VISkompakt objects description");
    textExtensions.put("vkp","Sony Ericsson firmware patch");
    textExtensions.put("vmg","Nokia saved text message");
    textExtensions.put("vna","NetDraw data");
    textExtensions.put("vsmproj","Microsoft Visual Studio unicode based macro project");
    textExtensions.put("vw","Volkswriter text document");
    textExtensions.put("vw3","Volkswriter 3 text file");
    textExtensions.put("vxml","VoiceXML source data");
    textExtensions.put("vzm","Verizon message");
    textExtensions.put("wer","Microsoft Windows application error report");
    textExtensions.put("wkf","KF Web Server default control");
    textExtensions.put("wn","NeXT WriteNow text document");
    textExtensions.put("wrd","COREX manually verified word segmentation data");
    textExtensions.put("wrl","VRML Worlds 3D graphics");
    textExtensions.put("wsh","Microsoft Windows Scripting Host data");
    textExtensions.put("wst","WordStar text");
    textExtensions.put("wtx","WinTune export text document");
    textExtensions.put("x20","XTree Gold for Dos help file");
    textExtensions.put("x60","XtreeGold for DOS help data");
    textExtensions.put("x70","XTree Gold for Dos help file");
    textExtensions.put("x80","Xtree Gold DOS help data");
    textExtensions.put("x90","XTree Gold for Dos help data");
    textExtensions.put("xc0","Xtree Gold for DOS help data");
    textExtensions.put("xdl","MS SQL Server XML schema file");
    textExtensions.put("xdp xdp","Acrobat XML data package");
    textExtensions.put("xfd","Adobe XFDL format XML form");
    textExtensions.put("xff","XFRX database output data");
    textExtensions.put("xhtm xhtm","Extensible HTML document");
    textExtensions.put("xlf","XLIFF document");
    textExtensions.put("xlog","Logging XML database log");
    textExtensions.put("xml xml","XML document");
    textExtensions.put("xmp xmp","Adobe Extensible Metadata Platform data");
    textExtensions.put("xsd xsd","XML schema description");
    textExtensions.put("xsl xsl","XML eXtensible stylesheet");
    textExtensions.put("xslt xslt","XSL transform data");
    textExtensions.put("xsr","FabTrol MRP data");
    textExtensions.put("xwp","XMLwriter project / Xerox Writer document");
    textExtensions.put("xy","XyWrite document");
    textExtensions.put("xy3","XYWrite III document");
    textExtensions.put("xyp","XY Write III Plus document");
    textExtensions.put("xyz","EOIS graph coordinates");
    textExtensions.put("yml","YAML document");
    textExtensions.put("zed","ZX-Edit document block");
    textExtensions.put("zhp","SwiftView ICS command data");
    textExtensions.put("zib","ZX-Editor graphic library");
    textExtensions.put("zw","Chinese text file");
    textExtensions.put("zxe","ZX-Editor Second Edition format");
  }
}
