#!/bin/bash

SCRIPT_PATH=$(dirname "$0")

# This script call the docrun task defined in the gradle.kts build
# The properties are passed via argument


if [[ ".$*" == "." ]]; then
	gradle docrun --project-dir "${SCRIPT_PATH}" -PcurrentDirectory="${PWD}"
else
	gradle docrun --project-dir "${SCRIPT_PATH%}" -PcurrentDirectory="${PWD}" -Parguments="$*"
fi
