version: '3'

includes:
  root:
    taskfile: ../Taskfile.yml
    flatten: true

tasks:
  unjar:
    cmds:
      - |
        cd target;
        rm -rf un-jar;
        mkdir un-jar;
        cd un-jar
        jar -xf ../tabulify-cli-0.1.0-SNAPSHOT.jar
  # Show the release config
  release-config:
    cmds:
      - |
        jreleaser config --git-root-search
  # Download jdks with the jdks maven plugin
  # Output: ${project.build.directory}/jdks
  # https://jreleaser.org/guide/latest/tools/jdks-maven.html
  jdks-setup:
    cmds:
      - |
        mvn jdks:setup-disco -P package > /dev/null
        echo "Jdks installed in <target/jdks>: "
        ls target/jdks/
  # List the configured Jdks
  # https://jreleaser.org/guide/latest/tools/jdks-maven.html
  jdks-list:
    cmds:
      - |
        mvn jdks:list-disco -P package
