alter table realm_mailing add column mailing_job_last_execution_time TIMESTAMP WITHOUT TIME ZONE NULL;
comment on column realm_mailing.mailing_job_last_execution_time is 'The last time a job was executed for this mailing';
alter table realm_mailing add column mailing_job_next_execution_time TIMESTAMP WITHOUT TIME ZONE NULL;
comment on column realm_mailing.mailing_job_next_execution_time is 'The next time that a job will execute for this mailing';
alter table realm_mailing add column mailing_count_row BIGINT NULL;
comment on column realm_mailing.mailing_count_row is 'The number of emails (ie users/email/row) for this mailing to send';
alter table realm_mailing add column mailing_count_row_success BIGINT NULL;
comment on column realm_mailing.mailing_count_row_success is 'The number of email send successfully (ie successful smtp transaction)';
alter table realm_mailing add column mailing_count_row_execution BIGINT NULL;
comment on column realm_mailing.mailing_count_row_execution is 'The number of smtp transfer execution (successful or not)';
