#!/bin/bash
# Run code in the code block of the tabli website and update the console block

set -TCEeuo pipefail

find_git_root() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.git" ]]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  echo "No .git directory found in any parent directory." >&2
  return 1
}

# Check if arguments are provided
if [ "$#" -lt 1 ]; then
    echo "Usage:"
    echo ""
    echo " $(basename "$0") --compile --ide --no-cache globPath"
    echo ""
    echo "where:"
    echo "  * --compile  : recompile the whole project"
    echo "  * --ide      : runs the Tabli.class instead of the tabli cli"
    echo "  * --no-cache : disable the doc cache "
    echo "  * globPath   : a glob path."
    echo ""
    echo "Example: $(basename "$0") docs/tabli/**/*.txt"
    exit 1
fi

MAVEN_COMPILE=false
IDE_RUN=false
DOC_EXEC_OPTIONS=();
while [ $# -gt 0 ]; do

   case "$1" in
      --compile)
          MAVEN_COMPILE=true
          ;;
      --ide)
        IDE_RUN=true
        DOC_EXEC_OPTIONS+=("$1")
        ;;
      *)
        DOC_EXEC_OPTIONS+=("$1")
   esac

    # Shift to the next argument
    shift
done

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT="$SCRIPT_DIR/../.."
cd "$PROJECT_ROOT/tabulify-cli"

# Extract main class from arguments
MAIN_CLASS=com.tabulify.doc.DocExec

if [ "$MAVEN_COMPILE" == "true" ]; then
  echo "Building project with Maven..."
  if ! (cd ..; mvn install -DskipTests > /dev/null); then
    echo "Maven Project build failed."
    exit 1
  fi
  # Compile the project using Maven (The DocRun class is in test)
  if ! mvn test-compile > /dev/null; then
      echo "Maven build failed."
      exit 1
  fi
fi

echo "Running $MAIN_CLASS..."

# Dependency
CLASSPATH=$(mvn dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q)

# Add the target/classes directory to include your compiled classes
CLASSPATH="$CLASSPATH:target/classes"
CLASSPATH="$CLASSPATH:target/test-classes"

export TABLI_ENV="dev";
if [ "$IDE_RUN" == "true" ]; then
  # When the code run as ide, tabli does not exit, it will throw
  # otherwise the doc executor security manager see it as executing and to prevent exit will throw
  TABLI_ENV="ide"
fi
# when sending not in production, it's mandatory
export TABLI_SMTP_TO=support@tabulify.com
export TABLI_SMTP_HOST
TABLI_SMTP_HOST=$(pass eraldy/mailpit-hostname)
export TABLI_SMTP_PORT=465
# the default but yeah
export TABLI_LOG_LEVEL=warn
# Exec
java -cp "$CLASSPATH" "$MAIN_CLASS" "${DOC_EXEC_OPTIONS[@]}"
