#!/usr/bin/env bash
# Install Tabulify locally
# at LOCAL_TABUL_HOME

set -TCEeuo pipefail

find_git_root() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.git" ]]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  echo "No .git directory found in any parent directory." >&2
  return 1
}


TABUL_HOME=${CLI_TABUL_HOME:-/opt/tabulify}

# Get, check if the parent directory exists
parent_dir=$(dirname "${TABUL_HOME}")
if [[ ! -d "${parent_dir}" ]]; then
    echo "Error: Parent directory '${parent_dir}' does not exist or is not a directory."
    exit 1
fi
# Get the owner of the parent directory
# stat gnu first, then stat macos
if ! path_owner=$(stat -c '%U' "${parent_dir}" 2>/dev/null); then
    # Try macOS/BSD stat format if Linux format fails
    if ! path_owner=$(stat -f '%Su' "${parent_dir}" 2>/dev/null); then
      echo "Error: Unable to determine ownership of parent directory '${parent_dir}'."
      exit 1
    fi
fi

# Compare the owner with the current user
current_user=$(whoami)
if [[ "${path_owner}" != "${current_user}" ]]; then
  echo "Parent directory '${parent_dir}' is owned by '${path_owner}', not by current user '${current_user}'. We can't install and move into it"
  exit 1
fi

# Determine the IDE project root
# and install the archive
PROJECT_ROOT=$(find_git_root)
(cd "$PROJECT_ROOT"; mvn install -DskipTests)

# Change context
TABULIFY_CLI_DIR=$(realpath "$PROJECT_ROOT/tabulify-cli")
cd "$TABULIFY_CLI_DIR"

# Create the release package
# Download the jdk, the deps
mvn clean package -DskipTests -P release


# Clean
# mkdir first as the tabulify dir should not exists, other the move command will copy the directory into
mkdir -p "$TABUL_HOME" && rm -rf "$TABUL_HOME"
ASSEMBLY_DIR=target/jreleaser/assemble/tabulify/jlink
rm -rf $ASSEMBLY_DIR

# Generate only for the current platform
export JRELEASER_PROJECT_VERSION
JRELEASER_PROJECT_VERSION=$(yq --exit-status '.project.version' ../pom.xml)
jreleaser assemble --debug --select-current-platform

# Move the jlink output
# No need to unzip - the dir is still there
ARCHIVE_VERSION_NAME=$JRELEASER_PROJECT_VERSION
# JReleaser change the archive name for snapshot
if [[ "$JRELEASER_PROJECT_VERSION" == *"-SNAPSHOT"* ]]; then
  ARCHIVE_VERSION_NAME=$(yq --exit-status '.project.snapshot.label' jreleaser.yml)
fi
ARCHIVE_NAME=tabulify-${ARCHIVE_VERSION_NAME}-linux-x86_64
ASSEMBLY_WORK_DIR=work-linux-x86_64
mv "${ASSEMBLY_DIR}/${ASSEMBLY_WORK_DIR}/${ARCHIVE_NAME}" "${TABUL_HOME}"
