#!/bin/bash
# Next Tabul: The next version of tabul

set -TCEeuo pipefail

NC='\033[0m'     # No Color
RED='\033[0;31m' # Red

function synopsis() {
  cat << EOF

  ntabul : Next tabul, run the next tabul version

      $(basename "$0") [options]

  Options:
    * -j | --java      : run the next java version (by default, it runs the distribution)
    * -i | --install   : install:
        * the distribution (distribution run)
        * or the jars (java run)

EOF
}

find_git_root() {
  local dir="$SCRIPT_DIR"
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.git" ]]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  echo "No .git directory found in any parent directory." >&2
  return 1
}

INSTALL=false
TABUL_OPTIONS=()
NEXT_TABUL_TYPE_DISTRIBUTION="distribution"
NEXT_TABUL_TYPE_JAVA="java"
NEXT_TABUL_TYPE=$NEXT_TABUL_TYPE_DISTRIBUTION
while [ $# -gt 0 ]; do

  case "$1" in
    -i | --install)
      INSTALL=true
      ;;
    -j | --java)
      NEXT_TABUL_TYPE="$NEXT_TABUL_TYPE_JAVA"
      ;;
    *)
      TABUL_OPTIONS+=("$1")
      ;;
  esac

  # Shift to the next argument
  shift
done

if [[ "${PROJECT_ROOT:-}" != *tabulify/tabulify ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # ntabul can be called from  everywhere
  # so to avoid clash, we compute the tabul PROJECT_ROOT
  PROJECT_ROOT=$(find_git_root)
fi

# Tabul home is important because it will be seen in the doc
# /opt/tabulify to have short path for the resource connection
# example for the howto: file:///opt/tabulify/resources/howto/
TABUL_HOME=${CLI_TABUL_HOME:-/opt/tabulify}

if [ "$NEXT_TABUL_TYPE" == "$NEXT_TABUL_TYPE_DISTRIBUTION" ]; then
  # Distribution installation

  if [ $INSTALL == true ]; then
    echo "Install distribution"
    install "$PROJECT_ROOT"
    echo "Install distribution done"
  else
    if [ ! -f "$TABUL_HOME/bin/tabul" ]; then
      echo "Tabul assembly not found at $TABUL_HOME/bin/tabul, installing" > /dev/stderr
      install "$PROJECT_ROOT"
    fi
  fi
  echo "Running tabul in $TABUL_HOME" > /dev/stderr
  if ! "${TABUL_HOME}/bin/tabul" "${TABUL_OPTIONS[@]}"; then
    echo -e "${RED}Error while running tabul in TABUL_HOME${NC}" > /dev/stderr
    exit 1
  fi
  exit
fi

echo "Running Tabul with Java (and Mvn classpath)" > /dev/stderr

CLI_PROJECT="cli-tabul"

# Main class
MAIN_CLASS=com.tabulify.tabul.Tabul

# Dependency
CLASSPATH=$(mvn dependency:build-classpath -pl "$CLI_PROJECT" -Dmdep.outputFile=/dev/stdout -q)

# Add the target/classes directory to include your compiled classes
CLASSPATH="$CLASSPATH:$PROJECT_ROOT/$CLI_PROJECT/target/classes"

if [ $INSTALL == true ]; then
  echo "Installing jars with Maven..."
  if ! OUTPUT=$(
    cd "$PROJECT_ROOT"
    mvn install -DskipTests
  ); then
    echo "$OUTPUT"
    echo "Maven Project install failed."
    exit 1
  fi
fi

# to get the stack, add TABUL_EXEC_ENV=ide
command="java -cp \"$CLASSPATH\" \"$MAIN_CLASS\" ${TABUL_OPTIONS[*]}"
eval "$command"

# Note: exec:java does not work, as it does not add the resources
# exec below will add the jar in the path that contains the services
# https://www.mojohaus.org/exec-maven-plugin/java-mojo.html
