#!/bin/bash
# Next Tabul: The next version of tabul
# Shortcut to run the tabul development version quickly after changing a class
# It will recompile optionally and run tabul without the need to create a jar

set -TCEeuo pipefail

find_git_root() {
  local dir="$SCRIPT_DIR"
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.git" ]]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  echo "No .git directory found in any parent directory." >&2
  return 1
}

MAVEN_COMPILE=false
TABUL_OPTIONS=()
while [ $# -gt 0 ]; do

  case "$1" in
    --compile)
      MAVEN_COMPILE=true
      ;;
    *)
      TABUL_OPTIONS+=("$1")
      ;;
  esac

  # Shift to the next argument
  shift
done

echo "Running Tabul with Java and Mvn classpath" > /dev/stderr

if [ "$PROJECT_ROOT" == "" ]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  PROJECT_ROOT=$(find_git_root)
fi
cd "$PROJECT_ROOT/cli-tabul"

# Extract main class from arguments
MAIN_CLASS=com.tabulify.tabul.Tabul

# Dependency
CLASSPATH=$(mvn dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q)

# Add the target/classes directory to include your compiled classes
CLASSPATH="$CLASSPATH:target/classes"

if [ "$MAVEN_COMPILE" == "true" ]; then
  echo "Building project with Maven..."
  if ! OUTPUT=$(
    cd "$PROJECT_ROOT"
    mvn install -DskipTests
  ); then
    echo "$OUTPUT"
    echo "Maven Project build failed."
    exit 1
  fi
fi

command="TABUL_ENV=ide java -cp \"$CLASSPATH\" \"$MAIN_CLASS\" ${TABUL_OPTIONS[*]}"
eval "$command"

# Note: exec:java does not work, as it does not add the resources
# exec below will add the jar in the path that contains the services
# https://www.mojohaus.org/exec-maven-plugin/java-mojo.html
