#!/usr/bin/env bash
# Tabulify Test
# See test.md

set -TCEeuo pipefail

NC='\033[0m'        # No Color
RED='\033[0;31m'    # Red

# Arg
RESUME_FROM=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    "--resume-from" | "-rf")
      shift
      RESUME_FROM="$1"
      shift
      ;;
    "--help" | "-h")
      echo "One option: --resume-from or -rf"
      exit 0
      ;;
    *)
      echo "Option $1 not known"
      exit 1
      ;;
  esac
done


# site goal and not test so that the reports are generated
ARGS=("clean" "site")
if [ "$RESUME_FROM" != "" ]; then
  ARGS+=("--resume-from" "$RESUME_FROM")
fi

if ! (command -v docker > /dev/null 2>&1 && docker info > /dev/null 2>&1); then
  echo -e "${RED}Error: docker is not available${NC}"
  exit 1
fi

if [ "$PROJECT_ROOT" == "" ]; then
  SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
  PROJECT_ROOT="$SCRIPT_DIR/../.."
fi

# Change context
(
  cd "$PROJECT_ROOT"
  mvnw "${ARGS[@]}"
)
