#!/usr/bin/env bash
# Create a tag

set -TCEeuo pipefail

NC='\033[0m'     # No Color
RED='\033[0;31m' # Red

function synopsis() {
  cat << EOF

  Release Tag:

      $(basename "$0") [options] [patch|minor|major|none]

  Args:
    * patch|minor|major|none : is the type of bump for the semver version (default to none - no bump)

  Options:
    * --dry-run : just shows the next tag and version

  The version is changed if the bump type is patch|minor|major

EOF
}

NO_BUMP_TYPE="none"
BUMP_TYPE="$NO_BUMP_TYPE"
DRY_RUN=true
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help | help)
      # Help
      doc::help synopsis
      exit 0
      ;;
    synopsis)
      # Doc Synopsis
      synopsis
      exit 0
      ;;
    -ndr | --no-dry-run)
      DRY_RUN=false
      ;;
    *)
      BUMP_TYPE="$1"
      shift
      break
      ;;
  esac
  shift
done

echo "Determining the version"
if [ "$BUMP_TYPE" != "$NO_BUMP_TYPE" ]; then
  echo "Version bump asked"
  # Get the next version
  export GIT_CLIFF__BUMP__INITIAL_TAG=v0.1.0 # by default it's 0.1.0
  if ! RELEASE_VERSION=$(git cliff --unreleased --context --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" --ignore-tags "v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]*" --bump "$BUMP_TYPE" | jq -r '.[0].version' | tr -d "v"); then
    echo -e "${RED}Error while getting the next version${NC}"
  fi
  # Jreleaser read the version from the pom file
  # We need to modify the pom file
  if [ $DRY_RUN == false ]; then
    echo "Creating Next version $RELEASE_VERSION commit"
    mvnw versions:set -DgenerateBackupPoms=false -DnewVersion="$RELEASE_VERSION"
    git commit -am "chore(release): $RELEASE_VERSION"
    git push origin
    echo "Next version $RELEASE_VERSION commit done"
  else
    echo "Dry Run, no commit done"
  fi
else
  echo "No bump taking the actual version"
  RELEASE_VERSION=$(yq '.project.version' pom.xml)
fi
echo "Version determined to be $RELEASE_VERSION"

IS_SNAPSHOT=true
if [[ ! "$RELEASE_VERSION" =~ .*-SNAPSHOT ]]; then
  IS_SNAPSHOT=false
fi

echo "Determining the tag"
if [[ $IS_SNAPSHOT == true ]]; then
  TAG_NAME="early-access"
else
  TAG_NAME="v$RELEASE_VERSION"
fi
echo "Tag determined to be $TAG_NAME"

if [ $DRY_RUN == false ]; then

  git-tag "$1"

else

  echo "Dry Run, no tag creation"

fi



# Next dev iteration
RELEASE_VERSION=$(git cliff --unreleased --bump "minor" --context --tag-pattern "v[0-9]+\\.[0-9]+\\.[0-9]+" | jq -r '.[0].version' | tr -d "v")
NEXT_SNAPSHOT_VERSION="$RELEASE_VERSION-SNAPSHOT"
echo "Next Iteration Commit to $NEXT_SNAPSHOT_VERSION"

if [[ $IS_SNAPSHOT == true ]]; then
  echo "Snapshot release, no next dev iteration. Exiting"
  exit
fi

if [[ $DRY_RUN == true ]]; then
  echo "Dry Run, no next commit"
else
  mvnw versions:set -DgenerateBackupPoms=false -DnewVersion="$NEXT_SNAPSHOT_VERSION"
  git commit -am "chore(next): $NEXT_SNAPSHOT_VERSION"
  git push origin
  echo "Next Iteration Commit to $NEXT_SNAPSHOT_VERSION: done"
fi
