#!/usr/bin/env bash
# Release Tabulify
# Test are starting containers with testcontainers
# Surefire is starting a JVM by module and testcontainers with Ryuk is deleting them
# when the jvm exit
# It means that we can just use mvnw as it's standard
#

set -TCEeuo pipefail

# Arg
RESUME_FROM=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    "--resume-from" | "-rf")
      shift
      RESUME_FROM="$1"
      shift
      ;;
    "--help" | "-h")
      echo "One option: --resume-from or -rf"
      exit 0
      ;;
    *)
      echo "Option $1 not known"
      exit 1
      ;;
  esac
done

ARGS=("test")
if [ "$RESUME_FROM" != "" ]; then
  ARGS+=("--resume-from" "$RESUME_FROM")
fi

if [ "$PROJECT_ROOT" == "" ]; then
  SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
  PROJECT_ROOT="$SCRIPT_DIR/../.."
fi

# Change context
(cd "$PROJECT_ROOT"; mvnw "${ARGS[@]}")


git cliff --bumped-version
