#!/bin/bash
# Shortcut to run tabli quickly after changing a class
# It will recompile and run tabli without the need to create a fat jar

set -TCEeuo pipefail

echo "Running Tabli with Mvn" > /dev/stderr

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT="$SCRIPT_DIR/../.."
cd "$PROJECT_ROOT/tabulify-cli"

# Extract main class from arguments
MAIN_CLASS=com.tabulify.tabli.Tabli

# Dependency
CLASSPATH=$(mvn dependency:build-classpath -Dmdep.outputFile=/dev/stdout -q)

# Add the target/classes directory to include your compiled classes
CLASSPATH="$CLASSPATH:target/classes"

command="java -cp \"$CLASSPATH\" \"$MAIN_CLASS\" $*"
eval "$command"

# Note: exec:java does not work, as it does not add the resources
# exec below will add the jar in the path that contains the services
# https://www.mojohaus.org/exec-maven-plugin/java-mojo.html
