# A template file with secret
# that should be copied to `.tower.secret.yml`
# and the xxxx values should be replaced by their respective values

# The Mixpanel project token
eraldy.mixpanel.project.token: 'xxxxx'

# Github
eraldy.api.oauth.github.client.id: 'xxxxx'
eraldy.api.oauth.github.client.secret: 'xxxxx'

# Google
eraldy.api.oauth.google.client.id: 'xxxxx'
eraldy.api.oauth.google.client.secret: 'xxxxx'
