#!/bin/bash

SCRIPT_PATH=$(dirname "$0")

# This script call the gradle task defined in the gradle.kts build
# The properties are passed via argument
RUN_GRADLE_TASK=runTowerHotReload

if [[ ".$*" == "." ]]; then
	"${SCRIPT_PATH}"/../gradlew "${RUN_GRADLE_TASK}" --project-dir "${SCRIPT_PATH}" -PcurrentDirectory="${PWD}"
else
	"${SCRIPT_PATH}"/../gradlew "${RUN_GRADLE_TASK}" --project-dir "${SCRIPT_PATH%}" -PcurrentDirectory="${PWD}" -Parguments="$*"
fi
