version: '3'

tasks:
  pg-start:
    cmds:
      - |
        docker run \
            -e POSTGRES_PASSWORD=welcome \
            -p 5432:5432 \
            -d \
            --name postgres \
            postgres:9.5
  pg-stop:
    cmds:
      - |
        docker stop postgres

